# Netlify config for Vite SPA (Blackout Web)

[build]
  command = "npm run build"
  publish = "dist"

# Set Node runtime used during build
[build.environment]
  NODE_VERSION = "18"

# SPA fallback so deep links work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Never cache the SPA shell
[[headers]]
  for = "/index.html"
  [headers.values]
  cache-control = "no-cache, no-store, must-revalidate"

# Cache hashed assets aggressively (Vite puts content hashes in filenames)
[[headers]]
  for = "/assets/*"
  [headers.values]
  cache-control = "public, max-age=31536000, immutable"
